export default {
  ADD_CONTACT: "ADD_CONTACT",
  
  ADD_CONTACT: "ADD_CONTACT_REQUEST",
  ADD_CONTACT: "ADD_CONTACT_SUCCSESS",
  ADD_CONTACT: "ADD_CONTACT_ERROR",




  DELETE_CONTACT: "DELETE_CONTACT",
  FILTER_CONTACT: "FILTER_CONTACT",
  CLEAR_ARRAY: "CLEAR_ARRAY",
};
